### ISSUE TITLE
Test Cases & Scenarios is incorrect

### ISSUE THREAD

**Issue by ckenst** [fityanos/awesome-quality-assurance-roadmap#20]
The section of understanding of Test Cases and Scenarios is incorrect:

> "Test Cases are clearly written and documented"
1. Depends on what test technique you are using. Some test techniques don't use written words, they use diagrams instead. Others like combinatorial and domain testing use only values (numbers, words, letters, characters, etc).
2. Unless you are doing old school, traditional test management, you shouldn't structure test cases as procedures. If you are mainly using exploratory testing your documentation will look a whole lot different than someone doing traditional test management. 

> "you can cover hire possibilities"
1. What does this mean?

**Comment by fityanos** [comment]
> The section of understanding of Test Cases and Scenarios is incorrect:
>
Test cases creation is not a mandatory step for each and every single test iteration, however, as a test engineer you should have a basic understanding of it, or else you will be running some random tests without a benchmark and release bugs.

P.S This roadmap is for the whole development community. Some people are not there yet in terms of skills and what is needed to start. Same as you documenting a readme file for a package, you should assume zero understanding.

> Unless you are doing old school, traditional test management, you shouldn't structure test cases as procedures. If you are mainly using exploratory testing your documentation will look a whole lot different than someone doing traditional test management.
>

Old school "AKA" as fundamentals are always and forever required to build the experience you need. I am not sure what a fresher would do if you mentor him

**Read the "About" section for this repository
The starting point of your career as a Software Quality Assurance Engineer | Quality Automation Engineer**

> What does this mean?
>
typo

**Comment by ckenst** [comment]
Just to be clear, old school doesn't mean fundamentals. Old school means taught in the 80s and in many cases no longer applicable, especially if you want to succeed today. I teach software testing fundamentals, I don't teach this.
